[package]
name = "flc-asm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
likely_stable = "0.1.3"
max78000 = { git = "https://github.com/slugsecurity/max78000" }
