[workspace]
members = [
    "hal",
    "flc-asm",
    "tests",
]
resolver = "2"

[profile.dev]
opt-level = "z"
codegen-units = 1

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
