name: fmt, clippy, rustdocs

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:    
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Run clippy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        cargo clippy -- -D warnings
        CARGO_NET_GIT_FETCH_WITH_CLI: true


  clippy-pedantic:
    runs-on: ubuntu-latest

    needs: clippy

    steps:
    - name: Run clippy (non-pedantic)
      run: cargo clippy -- -W clippy::pedantic

  format:
    runs-on: ubuntu-latest

    needs: [clippy, clippy-pedantic]
    steps:
      - name: Run format
        run: cargo fmt --check

  rustdoc:
    runs-on: ubuntu-latest

    needs: [clippy, clippy-pedantic, format]
    steps:
      - name: Run rustdoc
        run: cargo doc --no-deps --document-private-items
      - name : upload artifacts
        uses: actions/upload-artifact@v3
        with: 
            name: rustdoc
            path: target/doc
            retention-days: 2
