name: fmt, clippy, rustdocs

on: push

env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  add_ssh_keys:
    runs-on: ubuntu-latest
    steps:
    - name: Add ssh keys
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

  clippy:
    runs-on: ubuntu-latest

    needs: [add_ssh_keys]

    steps:
    - uses: actions/checkout@v3
    - name: Run clippy
      run: cargo clippy -- -D warnings

  clippy-pedantic:
    runs-on: ubuntu-latest

    needs: clippy

    steps:
    - name: Run clippy (non-pedantic)
      run: cargo clippy -- -W clippy::pedantic

  format:
    runs-on: ubuntu-latest

    needs: [clippy, clippy-pedantic]
    steps:
      - name: Run format
        run: cargo fmt --check

  rustdoc:
    runs-on: ubuntu-latest

    needs: [clippy, clippy-pedantic, format]
    steps:
      - name: Run rustdoc
        run: cargo doc --no-deps --document-private-items
      - name : upload artifacts
        uses: actions/upload-artifact@v3
        with: 
            name: rustdoc
            path: target/doc
            retention-days: 2
